---
# NOTE: "sudo: no" is needed because vagrant must be executed by a non-root user

- command: vagrant plugin update
  sudo: no

- command: vagrant plugin list
  sudo: no
  register: vagrant_plugin_lxc_installed
  changed_when: False

- command: vagrant plugin install vagrant-lxc
  sudo: no
  when: vagrant_plugin_lxc_installed.stdout.find('vagrant-lxc') == -1
