---
- shell: vagrant plugin list | grep -q vagrant-lxc
  sudo: no
  register: vagrant_plugin_lxc_installed
  failed_when: vagrant_plugin_lxc_installed.rc not in [0, 1]
  changed_when: False

# NOTE: "sudo: no" and sudo in command are needed to install correctly
# when running ansible-playbook on the VirtualBox VM
- command: sudo vagrant plugin install vagrant-lxc
  sudo: no
  when: vagrant_plugin_lxc_installed.rc == 1
