---
- file: path={{ lxc_container_vagrantfile_dir }} state=directory

- template: src=Vagrantfile.j2 dest={{ lxc_container_vagrantfile_dir }}/Vagrantfile

# NOTE: This "vagrant up" is successful only when I run this task on
# the VirtualBox VM, not on the VirtualBox Host (OSX).
#
# I got the following error when I run this task on the VirtualBox Host (OSX).
# failed: [default] => {"changed": true, "cmd": ["vagrant", "up"], "delta": "0:00:05.679316", "end": "2014-10-27 15:11:43.941264", "rc": 1, "start": "2014-10-27 15:11:38.261948"}
# stderr: The provider 'lxc' could not be found, but was requested to
# back the machine 'web1'. Please use a provider that exists.
# 
# FATAL: all hosts have already failed -- aborting
#
- command: vagrant up --provider lxc
    chdir={{ lxc_container_vagrantfile_dir }}
