---
- file: path={{ lxc_container_vagrantfile_dir }} state=directory
  sudo: no

- template: src=Vagrantfile.j2 dest={{ lxc_container_vagrantfile_dir }}/Vagrantfile
  sudo: no

# NOTE: "sudo: no" is needed because vagrant must be executed by a non-root user
- command: vagrant up --provider lxc
    chdir={{ lxc_container_vagrantfile_dir }}
  sudo: no
