- hosts: all
  gather_facts: yes
  sudo: yes
  roles:
    - apt_sources
    - apt_update
    - ntp
    - sysstat
    - vagrant
    - vagrant_lxc
    - role: lxc_container
      lxc_container_vagrantfile_dir: /vagrant/web1
      lxc_container_name: web1
      lxc_container_ip_address: 10.0.3.101
    - role: lxc_container
      lxc_container_vagrantfile_dir: /vagrant/web2
      lxc_container_name: web2
      lxc_container_ip_address: 10.0.3.102
